/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TaggerDemo */

#ifndef _Included_TaggerDemo
#define _Included_TaggerDemo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
